import os

class DataConfig(dict):
    def __init__(self, project_root: str, patch_size: int):
        super().__init__(
            # -------------- Pretraining datasets ------------------
            {'MHD': {'root':os.path.join(project_root, 'datasets', 
                            'normalized_revin', 'MHD3d_data_thewell'),
                    'fields':     3,
                    'components': 3,
                    'volume_size': (64, 64, 64),
                    'patch_size': (patch_size, patch_size, patch_size),
                    'max_patches': (64 // patch_size)**3,
                    'total_trsamples': 77, 
                    'total_timesteps': 100},
          'DR': {'root': os.path.join(project_root, 'datasets', 
                         'normalized_revin', 'DR2d_data_pdebench'),
                 'fields':     2,
                 'components': 1,
                 'volume_size': (1, 128, 128),
                 'patch_size': (1, patch_size, patch_size),
                 'max_patches': (128 // patch_size)**2,
                 'total_trsamples': 800, 
                 'total_timesteps': 101},
        'CFD1D': {'root': os.path.join(project_root, 'datasets', 
                          'normalized_revin', '1dcfd_pdebench'),
                 'fields':     3,
                 'components': 1,
                 'volume_size': (1, 1, 1024),
                 'patch_size': (1, 1, patch_size),
                 'max_patches': 1024 // patch_size,
                 'total_trsamples': 8000,
                 'total_timesteps': 100},
        'CFD2D-IC': {'root': os.path.join(project_root, 'datasets', 
                             'normalized_revin', '2dcfd_ic_pdebench'),
                 'fields':     1,
                 'components': 2,
                 'volume_size': (1, 512, 512),
                 'patch_size': (1, patch_size, patch_size),
                 'max_patches': (512 // patch_size)**2,
                 'total_trsamples': 4 * 16, 
                 'total_timesteps': 1000},
        'CFD3D': {'root': os.path.join(project_root, 'datasets', 
                          'normalized_revin', '3dcfd_pdebench'),
                 'fields':     3,
                 'components': 3,
                 'volume_size': (128, 128, 128),
                 'patch_size': (patch_size, patch_size, patch_size),
                 'max_patches': (128 // patch_size)**3,
                 'total_trsamples': 80 * 2, 
                 'total_timesteps': 21},
        'SW': {'root': os.path.join(project_root, 'datasets', 
                       'normalized_revin', '2dSW_pdebench'),
                 'fields':     1,
                 'components': 1,
                 'volume_size': (1, 128, 128),
                 'patch_size': (1, patch_size, patch_size),
                 'max_patches': (128 // patch_size)**2,
                 'total_trsamples': 800, 
                 'total_timesteps': 101},
       
        # -------------- Fine-tuning datasets ------------------
        'DR1D': {'root': os.path.join(project_root, 'datasets', 
                         'normalized_revin', '1ddr_pdebench'),
                 'fields':     1,
                 'components': 1,
                 'volume_size': (1, 1, 1024),
                 'patch_size': (1, 1, patch_size),
                 'max_patches': 128 // patch_size,
                 'total_trsamples': 8000, 
                 'total_timesteps': 101},
        
        'CFD2D': {'root': os.path.join(project_root, 'datasets', 
                          'normalized_revin', '2dcfd_pdebench'),
                 'fields':     3,
                 'components': 2,
                 'volume_size': (1, 512, 512),
                 'patch_size': (1, patch_size, patch_size),
                 'max_patches': (512 // patch_size)**2,
                 'total_trsamples': 8000, 
                 'total_timesteps': 21},
        
        'CFD3D-TURB': {'root': os.path.join(project_root, 'datasets', 
                         'normalized_revin', '3dcfd_turb_pdebench'),
                 'fields':     3,
                 'components': 3,
                 'volume_size': (64, 64, 64),
                 'patch_size': (patch_size, patch_size, patch_size),
                 'max_patches': (64 // patch_size)**3,
                 'total_trsamples': 480, 
                 'total_timesteps': 21},
        
        'BE1D': {'root': os.path.join(project_root, 'datasets', 
                          'normalized_revin', '1dbe_pdebench'),
                 'fields':     1,
                 'components': 1,
                 'volume_size': (1, 1, 1024),
                 'patch_size': (1, 1, patch_size),
                 'max_patches': 1024 // patch_size,
                 'total_trsamples': 8000, 
                 'total_timesteps': 201},
        
        'GSDR2D': {'root': os.path.join(project_root, 'datasets', 
                         'normalized_revin', '2dgrayscottdr_thewell'),
                 'fields':     2,
                 'components': 1,
                 'volume_size': (1, 128, 128),
                 'patch_size': (1, patch_size, patch_size),
                 'max_patches': (128 // patch_size)**2,
                 'total_trsamples': 160, 
                 'total_timesteps': 1001},
        
        'TGC3D': {'root': os.path.join(project_root, 'datasets', 
                          'normalized_revin', '3dturbgravitycool_thewell'),
                 'fields':     3,
                 'components': 3,
                 'volume_size': (64, 64, 64),
                 'patch_size': (patch_size, patch_size, patch_size),
                 'max_patches': (64 // patch_size)**3,
                 'total_trsamples': 80, 
                 'total_timesteps': 50},
        'FNS_KF_2D':{'root': os.path.join(project_root, 'datasets', 
                          'normalized_revin', '2dFNS_KF_pdegym'),
                 'fields':     1,
                 'components': 2,
                 'volume_size': (1, 128, 128),
                 'patch_size': (1, patch_size, patch_size),
                 'max_patches': (128 // patch_size)**2,
                 'total_trsamples': 16000, 
                 'total_timesteps': 21},
        
        }
            
            
                )